spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/blog?serverTimezone=Asia/Seoul
    driver-class-name: org.mariadb.jdbc.Driver
    username: user1
    password: user1

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false #jpa의 넘버링 전략을 따라가지 않음
    show-sql: true
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false
server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true


cos:
  key: cos1234


